---

- name: Zookeeper role execution play
  hosts: zookeepers
  become: true
  roles:
    - role: bilalcaliskan.zookeeper
      vars:
        log_path: /var/log/zookeeper
        data_dir_path: /var/lib/zookeeper
        enable_persistency: false

