---

- name: Apache Ignite role execution play
  hosts: all
  become: true
  roles:
    - geerlingguy.java
    - role: geerlingguy.elasticsearch
      vars:
        elasticsearch_version: "7.x"
        elasticsearch_package_version: "7.2.1"
        elasticsearch_package_state: present
        elasticsearch_service_state: started
        elasticsearch_service_enabled: true
        elasticsearch_network_host: "0.0.0.0"
        elasticsearch_http_port: 9200
        elasticsearch_heap_size_min: 1g
        elasticsearch_heap_size_max: 1g
        elasticsearch_extra_options: ""
