---

- name: Pre-installation tasks
  hosts: all
  serial: 100%
  become: true
  gather_facts: false
  pre_tasks:
    - name: Clean yum cache
      raw: dnf clean all && rm -rf /var/cache/yum
    - name: Ensure Python2 is installed on managed hosts
      raw: test -e /usr/bin/python2 || (dnf install -y python2)
    - name: Ensure Python3 is installed on managed hosts
      raw: test -e /usr/bin/python3 || (dnf install -y python3)
    - name: Set python3 is default python
      raw: echo 3 | alternatives --config python
  tasks:
    - name: Gather facts
      setup:
    - name: Import openvpn role
      import_role:
        name: openvpn
      tags: openvpn
