---

- name: Preparation role execution play
  hosts: all
  become: true
  vars:
    host_timezone: Europe/Istanbul
    timesync_ntp_provider: chrony
    # timesync_ntp_provider: ntp
  pre_tasks:
    - name: Ensure python-jmespath is installed
      yum:
        name: python-jmespath
        state: present
  post_tasks:
    - name: Set timezone
      timezone:
        name: "{{ host_timezone }}"
      notify: restart chrony
  handlers:
    - name: restart chrony
      service:
        name: chronyd
        state: restarted
  roles:
    - role: linux-system-roles.timesync
    - role: bilalcaliskan.vagrant_preparation

...
