---

- name: Zookeeper role execution play
  hosts: zookeepers
  become: true
  roles:
    - role: bilalcaliskan.zookeeper

- name: Kafka role execution play
  hosts: brokers
  become: true
  roles:
    - role: bilalcaliskan.kafka

