---

- name: Redis role execution play
  hosts: all
  become: true
  roles:
    - role: bilalcaliskan.redis
      vars:
        install_redis: true
        redis_max_memory: 250mb
        redis_enable_rdb: true
