---

- name: Redis role execution play
  hosts: all
  become: true
  roles:
    - role: bilalcaliskan.vagrant_preparation
      when: redis_install | bool
    - role: bilalcaliskan.redis
      vars:
        cluster_enabled: true
        sentinel_enabled: false
        redis_max_memory: 250mb
        redis_enable_rdb: true

...
